### ISSUE TITLE
Install on MacOS - Anaconda

### ISSUE THREAD

**Issue by neurolabusc** [SebastianoF/bruker2nifti#1]
Hello, I am trying to install this package on my MacOS 10.11.6 Python 2.7.11-0. I followed the instructions, but had to add `sudo` to `pip install -e .`. Things seems to install uneventully

```
$ python setup.py install
running install
running bdist_egg
running egg_info
writing bruker2nifti.egg-info/PKG-INFO
...
Processing dependencies for bruker2nifti==0.0.1
Finished processing dependencies for bruker2nifti==0.0.1
```
But I can not get this to run from the command line using the command in the README.md (note no '.py' extension)
```
$ python parsers/bruker2nii -h
python: can't open file 'parsers/bruker2nii': [Errno 2] No such file or directory
```
I was able to get a bit further by adding the '.py' extension, but it still generated an error
```
$ python parsers/bruker2nii.py -i /Users/rorden/tst/2 -o /Users/rorden/tst
Traceback (most recent call last):
  File "parsers/bruker2nii.py", line 105, in <module>
    main()
  File "parsers/bruker2nii.py", line 101, in main
    verbose=args.verbose
TypeError: convert_a_study() got an unexpected keyword argument 'qform'
```
I was also unable to start the GUI
```
$ ./gui_setupper_MAC.sh
create virtual environment, install the libraries and deactivate

Requirement already satisfied: virtualenv in /Users/rorden/anaconda/lib/python2.7/site-packages
New python executable in /Users/rorden/bruker2nifti/venv/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /Users/rorden/bruker2nifti/venv/bin/python - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/rorden/anaconda/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Users/rorden/anaconda/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/rorden/bruker2nifti/venv/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/rorden/bruker2nifti/venv/lib/python2.7/lib-dynload/_io.so
  Expected in: dynamic lookup

----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Users/rorden/anaconda/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/Users/rorden/anaconda/lib/python2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/Users/rorden/anaconda/lib/python2.7/site-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/Users/rorden/anaconda/lib/python2.7/site-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/Users/rorden/anaconda/lib/python2.7/site-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/rorden/bruker2nifti/venv/bin/python - setuptools pip wheel failed with error code 1
./gui_setupper_MAC.sh: line 17: venv/bin/activate: No such file or directory
```

**Comment by SebastianoF** [comment]
Thanks for the feedback!
Issue 1: missing .py added in the documentation! Unexpected keyword argument 'qform' problem hopefully solved - please update the repository with the latest version. There was a mistake I recently made changing a variable name in the core method and not in the wrapper.

You should as well use a different output folder, to avoid clash with the input one, and to avoid losing your data, in case something will go wrong (will put a warning message to avoid this in future version). Try something like:
```
mkdir /Users/rorden/tmp
python parsers/bruker2nii_scan.py -i /Users/rorden/tst/2 -o /Users/rorden/tmp
```
or to convert the whole study:
```
mkdir /Users/rorden/tmp
python parsers/bruker2nii.py -i /Users/rorden/tst -o /Users/rorden/tmp -study_name my_study
```

Issue 2: about starting the GUI, what I proposed is not Anaconda compatible, that relates to the issue you had with 'sudo pip'. 
Conda creates a parallel version of python leaving untouched the system Python (Good). But it also uses its own terminology (bad). So when you call pip, it may still call the native package manager under /System/Library of the native python (try to type 'type pip' to see if it is the case), or some other python that has nothing to do with the virtualenv you created with conda.
You will have to re-tune the whole thing for conda.
To start the GUI, try to do:
```
cd where_you_have_the_code
conda create -n venv python=2.7 anaconda
source activate venv
conda install -r requirements.txt
python open_GUI.py
 ```
Please let me know.

**Comment by neurolabusc** [comment]
It fails because it can not find a 'subject' file - none of my Bruker data has 'subject' files:
```
$ python parsers/bruker2nii.py -i /Users/rorden/tst/2 -o /Users/rorden/tmp
2/
    .DS_Store
    acqp
    AdjStatePerScan
    configscan
    fid
    method
    pulseprogram
    specpar
    spnam40
    uxnmr.info
    uxnmr.par
    visu_pars
    pdata/
        .DS_Store
        1/
            2dseq
            id
            procs
            reco
            roi
            visu_pars
File /Users/rorden/tst/2/subject does not exists
Traceback (most recent call last):
  File "parsers/bruker2nii.py", line 105, in <module>
    main()
  File "parsers/bruker2nii.py", line 101, in main
    verbose=args.verbose
  File "build/bdist.macosx-10.5-x86_64/egg/bruker2nifti/study_converter.py", line 84, in convert_a_study
  File "build/bdist.macosx-10.5-x86_64/egg/bruker2nifti/_getters.py", line 47, in get_subject_name
```

**Comment by SebastianoF** [comment]
If I understood correctly how conda works, to get the GUI with anaconda on MAC, you may need to switch the content of run_GUI_setupper_MAC.sh with the following code:
```
#!/bin/sh

# simple bash script to create a gui 'launcher'.
# Location of the launcher can be changed, copy-pasted and moved around
# location of the bruker2nifti folder cannot be moved!!


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

echo
echo 'create virtual environment, install the libraries and deactivate'
echo

conda info
conda create -n venv python=2.7 anaconda
source activate venv
conda install -n vevn -r requirements.txt
source deactivate

echo
echo 'select paths required to have the python of the virtualenvironment'
echo


DIR_PY=//anaconda/envs/venv/bin/python
CALLER=$DIR/$DIR_PY
EXEC=$DIR/open_GUI.py

echo
echo 'generate launcher-like and add permission'
echo


echo '#!/bin/sh' > runGUIbru2nii
echo $CALLER $EXEC >> runGUIbru2nii
chmod +x runGUIbru2nii
```
If it works it makes it a bit of an overkill, as anaconda installs a huge amount of libraries that are not used by the converter.
To avoid this you can bypass the virtualenv, and use directly your conda-installed python.
You will have to install the libraries in the requirements first, and then use this script instead:
```
#!/bin/sh

# simple bash script to create a gui 'launcher'.
# Location of the launcher can be changed, copy-pasted and moved around
# location of the bruker2nifti folder cannot be moved!!


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

echo
echo 'select paths required to have the python of the virtualenvironment'
echo

CALLER="$(which python)"
EXEC=$DIR/open_GUI.py

echo
echo 'generate launcher-like and add permission'
echo


echo '#!/bin/sh' > runGUIbru2nii
echo $CALLER $EXEC >> runGUIbru2nii
chmod +x runGUIbru2nii

```
Let me know if it works. About the subject file not found please open another thread.

**Comment by neurolabusc** [comment]
Regarding your earlier comments, is it possible you meant `--file `not` -r`, regardless both generate errors.
```
$ conda install --r requirements.txt
Error: expected revision number, not: 'requirements.txt'
$ conda install --file requirements.txt
Fetching package metadata: ....
Error: No packages found in current osx-64 channels matching: nibabel >=2.1.0
You can search for this package on anaconda.org with
    anaconda search -t conda nibabel >=2.1.0
$ anaconda search -t conda nibabel >=2.1.0
Using Anaconda API: https://api.anaconda.org
$ conda install --file requirements.txt
Fetching package metadata: ....
Error: No packages found in current osx-64 channels matching: nibabel >=2.1.0
You can search for this package on anaconda.org with
    anaconda search -t conda nibabel >=2.1.0
```

**Comment by SebastianoF** [comment]
Thanks, '--file' seems correct; updated above.
It seems nibabel has a different installation modality in conda:
https://anaconda.org/conda-forge/nibabel
Try:
```
conda install -c conda-forge nibabel
```

**Comment by neurolabusc** [comment]
```
$ python parsers/bruker2nii.py -i /Users/rorden/tst/2 -o /Users/rorden/tmp
Traceback (most recent call last):
  File "parsers/bruker2nii.py", line 2, in <module>
    from bruker2nifti.study_converter import convert_a_study
ImportError: No module named bruker2nifti.study_converter

```

**Comment by SebastianoF** [comment]
Uhm... If the installation of the code as a library on your local python distribution did not happened, you have to be in the root of the code to see the module bruker2nifti.study_converter to make it work:
```
cd folder_where_you_have_the_code
python parsers/bruker2nii.py -i /Users/rorden/tst/2 -o /Users/rorden/tmp
```
Where the `python` in the previous command needs to refer to a python where you installed the required libraries, wether in a virtualenvironment, in a conda virtualenvironment, in the default conda distribution or somewhere else. 

Alternatively you can add the code to your python-path:
https://www.techwalla.com/articles/how-to-set-your-python-path

**Comment by neurolabusc** [comment]
I seem to be in the root folder for bruker2nifti, as shown by calls to `ls`

```
(venv)Chriss-MBP:bruker2nifti rorden$ ls
=2.1.0			build			gui_run_setupper_LINUX	parsers			simple.sh
LICENCE.txt		complex.sh		gui_run_setupper_MAC	requirements.txt	test
README.md		definitions.py		gui_setupper_LINUX.sh	runGUIbru2nii		test_data
bruker2nifti		definitions.pyc		gui_setupper_MAC.sh	screenshots		venv
bruker2nifti.egg-info	dist			open_GUI.py		setup.py
(venv)Chriss-MBP:bruker2nifti rorden$ git pull
Already up-to-date.
(venv)Chriss-MBP:bruker2nifti rorden$ conda install -c conda-forge nose
Fetching package metadata: ......
Solving package specifications: ...............
Package plan for installation in environment /Users/rorden/anaconda/envs/venv:

The following packages will be UPDATED:

    python:     2.7.13-0      --> 2.7.13-1     
    setuptools: 27.2.0-py27_0 --> 33.1.1-py27_0
    sqlite:     3.13.0-0      --> 3.13.0-1     
    tk:         8.5.18-0      --> 8.5.19-1     
    zlib:       1.2.8-3       --> 1.2.11-0     

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|###############################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|###############################################################################################################| 100%
(venv)Chriss-MBP:bruker2nifti rorden$ conda install -c conda-forge nibabel
Fetching package metadata: ......
Solving package specifications: ......................................
# All requested packages already installed.
# packages in environment at /Users/rorden/anaconda/envs/venv:
#
nibabel                   2.1.0                    py27_0    https://conda.binstar.org/conda-forge/osx-64/nibabel-2.1.0-py27_0.tar.bz2
(venv)Chriss-MBP:bruker2nifti rorden$ conda install -c anaconda numpy
Fetching package metadata: ......
Solving package specifications: ..............
Package plan for installation in environment /Users/rorden/anaconda/envs/venv:

The following packages will be DOWNGRADED:

    python:     2.7.13-1      --> 2.7.13-0     
    setuptools: 33.1.1-py27_0 --> 27.2.0-py27_0
    sqlite:     3.13.0-1      --> 3.13.0-0     
    tk:         8.5.19-1      --> 8.5.18-0     
    zlib:       1.2.11-0      --> 1.2.8-3      

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|###############################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|###############################################################################################################| 100%
(venv)Chriss-MBP:bruker2nifti rorden$ conda install -c anaconda setuptools
Fetching package metadata: ......
Solving package specifications: ............
# All requested packages already installed.
# packages in environment at /Users/rorden/anaconda/envs/venv:
#
setuptools                27.2.0                   py27_0  
(venv)Chriss-MBP:bruker2nifti rorden$ conda install -c anaconda sympy
Fetching package metadata: ......
Solving package specifications: ..............
Package plan for installation in environment /Users/rorden/anaconda/envs/venv:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mpmath-0.19                |           py27_1         873 KB
    sympy-1.1                  |           py27_0         6.2 MB
    ------------------------------------------------------------
                                           Total:         7.1 MB

The following NEW packages will be INSTALLED:

    mpmath: 0.19-py27_1
    sympy:  1.1-py27_0 

Proceed ([y]/n)? y

Fetching packages ...
mpmath-0.19-py 100% |############################################################################################| Time: 0:00:00   3.16 MB/s
sympy-1.1-py27 100% |############################################################################################| Time: 0:00:00   6.88 MB/s
Extracting packages ...
[      COMPLETE      ]|###############################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|###############################################################################################################| 100%
(venv)Chriss-MBP:bruker2nifti rorden$ python parsers/bruker2nii.py -i /Users/rorden/tst/2 -o /Users/rorden/tmp -study_name my_study
Traceback (most recent call last):
  File "parsers/bruker2nii.py", line 2, in <module>
    from bruker2nifti.study_converter import convert_a_study
ImportError: No module named bruker2nifti.study_converter
(venv)Chriss-MBP:bruker2nifti rorden$ ls
=2.1.0			build			gui_run_setupper_LINUX	parsers			simple.sh
LICENCE.txt		complex.sh		gui_run_setupper_MAC	requirements.txt	test
README.md		definitions.py		gui_setupper_LINUX.sh	runGUIbru2nii		test_data
bruker2nifti		definitions.pyc		gui_setupper_MAC.sh	screenshots		venv
bruker2nifti.egg-info	dist			open_GUI.py		setup.py
```

**Comment by SebastianoF** [comment]
You are absolutely right!
I forgot a step and I updated the answer afterwards.
The interpreter does not see bruker2nifti.
While still in the environment, try this:
```
conda install -n vevn pip
# install bruker2nifti as a local library:
pip install -e .
# try if python is really in the virtualenv:
which python
# try if the parser works:
python parsers/bruker2nii.py -i /Users/rorden/tst/2 -o /Users/rorden/tmp -study_name my_study
```

**Comment by SebastianoF** [comment]
I actually forgot as well in the README the fact that you need to add the code to the PYTHONPATH if the code is not installed. To run the converter from the code from command line through parser without installing:
Add the code to the PYTHONPATH:
```
PYTHONPATH="${PYTHONPATH}:path-to-bruker2nifti
```
then run the code
```
python parsers/bruker2nii.py -i /Users/rorden/tst/2 -o /Users/rorden/tmp -study_name my_study
```
Where python is any python (venv, conda, etc...) with the libraries in the requirements.txt installed. 
@neurolabusc many thanks for the feedback!!

**Comment by neurolabusc** [comment]
OK, the command line version works now. Despite your help, I still did not get the GUI version working, but this probably reflects my Python distribution. Thanks for your nice tool. It looks like it does a good job on converting the sample https://github.com/naveau/bruker2nifti_qa. I also used your code to update my Bru2Nii, so it no longer requires RECO files. You might want to update your README.md to reflect this.

**Comment by SebastianoF** [comment]
Now bruker2nifti is pip-installable. Should be installable also with anaconda distributions (did not tested though), still using pip. Please create a conda environment and then type 
```
pip install bruker2nifti
bruker2nifti_gui
```
The second command should finally open the GUI, while
```
bruker2nifti -h
```
Should open the help of the command line interface.
