### ISSUE TITLE
Python 3 installation working in development mode, not working if installed with pip

### ISSUE THREAD

**Issue by SebastianoF** [SebastianoF/bruker2nifti#41]
The converter works with Python 3 if installed in development mode.
Travis-CI tests are all passed.

Not working if installed with pip:

```
(virtualenv_with_python3)  $ pip install bruker2nifti
Collecting bruker2nifti
  Using cached https://files.pythonhosted.org/packages/80/ea/85b6727a3d097333e96b4e54cefe641cfeef46613d2219f2b370128ae20a/bruker2nifti-0.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gt/1wq0q3rd0ls798jvlgc0n9fm0000gn/T/pip-install-ds6c04km/bruker2nifti/setup.py", line 39, in <module>
        install_requires=requirements2list(),
      File "/private/var/folders/gt/1wq0q3rd0ls798jvlgc0n9fm0000gn/T/pip-install-ds6c04km/bruker2nifti/setup.py", line 8, in requirements2list
        f = open(pfi_txt, 'r')
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/gt/1wq0q3rd0ls798jvlgc0n9fm0000gn/T/pip-install-ds6c04km/bruker2nifti/
```

Probably the version on pypi (https://pypi.org/search/?q=bruker2nifti) is not compatible, and not up to date with the intended version.

**Comment by SebastianoF** [comment]
Fixed from version 1.0.3
