### ISSUE TITLE
numpy 1.12.0 rejects floats as reshape arguments

### ISSUE THREAD

**Issue by gdevenyi** [SebastianoF/bruker2nifti#43]
This section of code
https://github.com/SebastianoF/bruker2nifti/blob/master/bruker2nifti/_getters.py#L161-L166

Dies on numpy 1.12.0 with the following error:

```
/home/cic/desgab/Desktop/bruker2nifti_qa-master/raw/McGill_Orientation/a20130329_APM_DEV_Orient.j71
started:


Converting experiment 1:

pdata/
   1/
       d3proc
       id
       meta
       roi
       2dseq
       visu_pars
       procs
       reco
Traceback (most recent call last):
 File "test_b2n.py", line 9, in <module>
   bru.convert()
 File "/home/cic/desgab/Desktop/bruker2nifti/bruker2nifti/converter.py", line 185, in convert
   nifti_file_name=scan_name)
 File "/home/cic/desgab/Desktop/bruker2nifti/bruker2nifti/converter.py", line 137, in convert_scan
   get_reco=self.get_reco,
 File "/home/cic/desgab/Desktop/bruker2nifti/bruker2nifti/_cores.py", line 150, in scan2struct
   consider_subject_position=consider_subject_position
 File "/home/cic/desgab/Desktop/bruker2nifti/bruker2nifti/_getters.py", line 166, in nifti_getter
   vol_data = img_data_vol.reshape(vol_pre_shape, order='F')
TypeError: 'numpy.float64' object cannot be interpreted as an integer

```

**Comment by gdevenyi** [comment]
Notes here: https://github.com/numpy/numpy/releases/tag/v1.12.0

**Comment by SebastianoF** [comment]
Thanks! Maybe solved on the `dev` branch.
Can you please check if it works on your side, as I could not reproduce the error with my current dataset.

**Comment by gdevenyi** [comment]
Still bugged, now with a reshape problem
```
/home/cic/desgab/Desktop/bruker2nifti_qa-master/raw/McGill_Orientation/a20130329_APM_DEV_Orient.j71
started:


Converting experiment 1:

pdata/
   1/
       d3proc
       id
       meta
       roi
       2dseq
       visu_pars
       procs
       reco
Traceback (most recent call last):
 File "test_b2n.py", line 9, in <module>
   bru.convert()
 File "/home/cic/desgab/Desktop/bruker2nifti/bruker2nifti/converter.py", line 185, in convert
   nifti_file_name=scan_name)
 File "/home/cic/desgab/Desktop/bruker2nifti/bruker2nifti/converter.py", line 137, in convert_scan
   get_reco=self.get_reco,
 File "/home/cic/desgab/Desktop/bruker2nifti/bruker2nifti/_cores.py", line 150, in scan2struct
   consider_subject_position=consider_subject_position
 File "/home/cic/desgab/Desktop/bruker2nifti/bruker2nifti/_getters.py", line 167, in nifti_getter
   vol_data = img_data_vol.reshape(vol_pre_shape, order='F')
ValueError: cannot reshape array of size 66 into shape (256,256,15,0)
```

**Comment by SebastianoF** [comment]
Uhm... It seems that the information in the Bruker parameters files does not match the dimension of the array. Try to copy your data in a new place, erase folder 1 and see if the other subjects are converted correctly. So I will know how much do I have to worry :-) ! Let me know.

**Comment by gdevenyi** [comment]
BTW, this is the test data from the repo....

```
Study conversion
/home/cic/desgab/Desktop/bruker2nifti_qa-master/raw/McGill_Orientation/a20130329_APM_DEV_Orient.j71
started:


Converting experiment 2:

pdata/
   1/
       d3proc
       meta
       2dseq
       procs
       visu_pars
       roi
       id
       reco
Traceback (most recent call last):
 File "test_b2n.py", line 9, in <module>
   bru.convert()
 File "/home/cic/desgab/Desktop/bruker2nifti/bruker2nifti/converter.py", line 185, in convert
   nifti_file_name=scan_name)
 File "/home/cic/desgab/Desktop/bruker2nifti/bruker2nifti/converter.py", line 137, in convert_scan
   get_reco=self.get_reco,
 File "/home/cic/desgab/Desktop/bruker2nifti/bruker2nifti/_cores.py", line 150, in scan2struct
   consider_subject_position=consider_subject_position
 File "/home/cic/desgab/Desktop/bruker2nifti/bruker2nifti/_getters.py", line 167, in nifti_getter
   vol_data = img_data_vol.reshape(vol_pre_shape, order='F')
ValueError: cannot reshape array of size 65 into shape (64,64,32,0)
```

**Comment by SebastianoF** [comment]
Looks odd. I will be looking into it in the week end.

**Comment by gdevenyi** [comment]
I am unable to reproduce my user's errors in a clean environment, so I'm considering the original bug fixed and closed. Thanks.

**Comment by gdevenyi** [comment]
Followup: error due to user not having git-lfs when getting a copy of the QA repo.
